/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import static java.awt.event.MouseEvent.MOUSE_CLICKED;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.Document;


/**
 *
 * @author proxc
 */
public class Nouveau_Membre extends javax.swing.JFrame {

    /**
     * Creates new form Home_Data
     */
    public    int id_membre_update=-1;

    public Nouveau_Membre() throws SQLException {
        initComponents();
       // new new_cotisation().loadCombo(jComboBox_membre);
        Jmatricule.setVisible(false);
        jLabel_membre.setVisible(false);
        jToggleButton2.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        JLnumero = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        JLMatricule = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        JLnom = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        JLprenom = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        JLadresse = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        JLposte = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Btn_Soumettre = new javax.swing.JButton();
        Btn_Annuler = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_etat = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_membre = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        Jmatricule = new javax.swing.JTextField();
        avertissement_matricule = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icon_add1.png"))); // NOI18N
        jLabel15.setText("Ajouter Membre");

        exit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 0, 0));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_Exit_25px.png"))); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(45, 118, 232));
        jPanel7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Matricule");

        JLnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLnumeroActionPerformed(evt);
            }
        });
        JLnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JLnumeroKeyTyped(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Numéro de téléphone");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Poste");

        JLnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JLnomKeyTyped(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Adresse");

        JLprenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JLprenomKeyTyped(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Prénom ");

        JLadresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLadresseActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nom");

        JLposte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JLposteKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Nouveau membre ");

        Btn_Soumettre.setBackground(new java.awt.Color(153, 153, 153));
        Btn_Soumettre.setText("Soumettre");
        Btn_Soumettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SoumettreActionPerformed(evt);
            }
        });

        Btn_Annuler.setBackground(new java.awt.Color(255, 51, 51));
        Btn_Annuler.setText("Annuler");
        Btn_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AnnulerActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("État");

        jComboBox_etat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "actif", "inactif" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel22))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JLprenom)
                                    .addComponent(JLnom)
                                    .addComponent(JLadresse, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(JLnumero)
                                    .addComponent(JLposte)
                                    .addComponent(JLMatricule)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox_etat, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Btn_Annuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Soumettre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLadresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLposte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox_etat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Annuler)
                    .addComponent(Btn_Soumettre))
                .addGap(16, 16, 16))
        );

        jToggleButton1.setText("Modifier infos membres");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/iconR41.jpeg"))); // NOI18N

        jLabel_membre.setText("Entrer la matricule: ");

        jToggleButton2.setText("Voir infos ");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        Jmatricule.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_membre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jmatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avertissement_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_membre)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jmatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avertissement_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SoumettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SoumettreActionPerformed
        // TODO add your handling code here:
      String nom = JLnom.getText();
      String prenom=JLprenom.getText();
      String poste = JLposte.getText();
      
      String adresse=JLadresse.getText();
      String matricule=JLMatricule.getText();
      String etat= (String) jComboBox_etat.getSelectedItem();
        if(nom.equals("")|| prenom.equals("")||poste.equals("")||JLnumero.getText().equals("")||adresse.equals("")||matricule.equals("") )
        {
         JOptionPane.showMessageDialog(this,"VEUILLER REMPLIR TOUS LES CHAMPS ","ERREUR!!",JOptionPane.INFORMATION_MESSAGE,null);
         return ;

          
        }
        else if(Btn_Soumettre.getText().equals("Soumettre"))
        {
           int numero = Integer.parseInt(JLnumero.getText());
          Membre M= new Membre(prenom,nom,poste,matricule,adresse,numero,etat);  
          try{
            
              int res= new Database_Connect().SaveMembreOnDB(M);
            
              if(res==0){
                  cleanLabel();
                 JOptionPane.showMessageDialog(this,"Un nouveau membre a été bien ajouté ","Notification !!",JOptionPane.INFORMATION_MESSAGE,null);
                 return ;   
              }
              else{
                  JOptionPane.showMessageDialog(this,"La matricule existe déjà !!! Veuillez en prendre une autre ","ERREUR!!",JOptionPane.INFORMATION_MESSAGE,null);
                 return ;
              }
            
          }
          catch(SQLException sl){
              //System.out.println("Hakaza Falll");
             
          }

            
        }
        else if(Btn_Soumettre.getText().equals("Modifier")){
            int numero = Integer.parseInt(JLnumero.getText());
            Membre M= new Membre(prenom,nom,poste,matricule,adresse,numero,etat); 
          try {
              new Database_Connect().UpdateMembreOnDB(M,id_membre_update);
          } catch (SQLException ex) {
              Logger.getLogger(Nouveau_Membre.class.getName()).log(Level.SEVERE, null, ex);
          }
           
            Btn_Soumettre.setText("Soumettre");
          
            Jmatricule.setVisible(false);
            jLabel_membre.setVisible(false);
            jToggleButton2.setVisible(false);
            jLabel22.setText("Nouveau Membre");
            JLMatricule.setText("");
            JLadresse.setText("");JLnom.setText("");
            JLnumero.setText("");JLposte.setText("");
            JLprenom.setText("");
            Jmatricule.setText("");
            id_membre_update=0;
            JOptionPane.showMessageDialog(this,"Les informations du membre ont été bien modifiées ","Notification !!",JOptionPane.INFORMATION_MESSAGE,null);
            return ;
        }

    }//GEN-LAST:event_Btn_SoumettreActionPerformed

    private void cleanLabel(){
        JLMatricule.setText("");
            JLadresse.setText("");JLnom.setText("");
            JLnumero.setText("");JLposte.setText("");
            JLprenom.setText("");
    }
    private void Btn_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AnnulerActionPerformed
        // TODO add your handling code here:
        clearMemberForm();
        Jmatricule.setVisible(false);
        jLabel_membre.setVisible(false);
        jToggleButton2.setVisible(false);

        
    }//GEN-LAST:event_Btn_AnnulerActionPerformed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        if(JLMatricule.getText().equals("") &&
        JLadresse.getText().equals("") && JLnom.getText().equals("") &&
        JLnumero.getText().equals("") && JLposte.getText().equals("") &&
        JLprenom.getText().equals("") )
        {
                this.setVisible(false);

        }
        else
        {       
            //JOptionPane.showMessageDialog(this," Voulez-vous vraiment quitter sans enregistrer!","Notification !!",JOptionPane.INFORMATION_MESSAGE,null);
            int res=showConfirmDialog();
            if(res==0){
                this.setVisible(false);
  
            }
            else{

            }

        }
        
    }//GEN-LAST:event_exitMousePressed

    private void JLprenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JLprenomKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JLprenomKeyTyped

    private void JLnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JLnumeroKeyTyped
        // TODO add your handling code here:
        keyTyped(evt);
    }//GEN-LAST:event_JLnumeroKeyTyped

    private void JLnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JLnomKeyTyped
        // TODO add your handling code here:
                keyTyped2(evt);

    }//GEN-LAST:event_JLnomKeyTyped

    private void JLposteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JLposteKeyTyped
        // TODO add your handling code here:
        keyTyped2(evt);
    }//GEN-LAST:event_JLposteKeyTyped

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        Jmatricule.setVisible(true);
       
        jLabel_membre.setVisible(true);
        jToggleButton2.setVisible(true);
        jToggleButton1.setBackground(Color.gray);
        //jPanel7.setBackground(Color.black);
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
    // TODO add your handling code here:
        String membre = (String) Jmatricule.getText();

        if(!membre.equals("")){
            

            try {
                ResultSet rs= new Database_Connect().returnMemberInfos(membre);
                remplirMembreInfos(rs);

            } catch (SQLException ex) {
                Logger.getLogger(Nouveau_Membre.class.getName()).log(Level.SEVERE, null, ex);
            }
     
        }
        else
                     JOptionPane.showMessageDialog(this,"Veuiller renseigner la matricule !!! ","ATTENTION !!",JOptionPane.INFORMATION_MESSAGE,null);   

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void JLadresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLadresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JLadresseActionPerformed

    private void JLnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JLnumeroActionPerformed
    public void keyTyped(KeyEvent k)  
     {  
         // cette methode permet le refus d'entrer de lettre sur un champ !!
      if (! Character.isDigit(k.getKeyChar()))  
      {  
       k.consume();
      }    
    }
    public void keyTyped2(KeyEvent e) {
      // cette methode permet le refus d'entrer des caracteres speciales  !!
        char c = e.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c!=KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE ))
        {
            e.consume();  // ignorer l'événement
        }
    }
    
    public void remplirMembreInfos(ResultSet rs) throws SQLException{
        if(rs.next()){
            avertissement_matricule.setText("");
            JLprenom.setText(rs.getString("prenom"));
            JLnom.setText(rs.getString("nom"));
            JLadresse.setText(rs.getString("adresse"));
            JLMatricule.setText(rs.getString("matricule"));
            JLposte.setText(rs.getString("poste"));
            JLnumero.setText(rs.getString("numero"));
            jComboBox_etat.setSelectedItem(rs.getString("etat"));
            id_membre_update=Integer.parseInt(rs.getString("id"));
            Btn_Soumettre.setText("Modifier");
            jLabel22.setText("Modifier Membre");
            System.out.println(Btn_Soumettre.getActionCommand());

        }
        else{
            clearMemberForm();
            avertissement_matricule.setText("Erreur cette matricule n'existe pas!");  
        }


    }
   
    public void clearMemberForm(){
        // Cette methode permet de vider les champs du formulaire d'ajout ou de modification 
        jLabel22.setText("Nouveau Membre");
        Btn_Soumettre.setText("Soumettre");
        jToggleButton1.setBackground(Color.WHITE);
        JLMatricule.setText("");
        JLadresse.setText("");JLnom.setText("");
        JLnumero.setText("");JLposte.setText("");
        JLprenom.setText("");
        avertissement_matricule.setText("");
        
    }
    static int showConfirmDialog(){
         
        return JOptionPane.showConfirmDialog(
        null,
        "Vous n'avez pas enregistrer \n Voulez-vous vraiment quitter ?",
        "Quitter",
        JOptionPane.YES_NO_OPTION);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nouveau_Membre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nouveau_Membre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nouveau_Membre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nouveau_Membre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Nouveau_Membre().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Nouveau_Membre.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Annuler;
    private javax.swing.JButton Btn_Soumettre;
    private javax.swing.JTextField JLMatricule;
    private javax.swing.JTextField JLadresse;
    private javax.swing.JTextField JLnom;
    private javax.swing.JTextField JLnumero;
    private javax.swing.JTextField JLposte;
    private javax.swing.JTextField JLprenom;
    private javax.swing.JTextField Jmatricule;
    private javax.swing.JLabel avertissement_matricule;
    private javax.swing.JLabel exit;
    private javax.swing.JComboBox<String> jComboBox_etat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel_membre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
